# Jekyll Theme Settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Site Settings
title: "Моё резюме"
subtitle: "Онлайн-версия"
name: "Яковлев Юрий Олегович"
description: "Добро пожаловать"
locale: "ru-RU"
time: "1993"
breadcrumbs: true
search: true

# Site Author
author:
  name   : "Яковлев Юрий Олегович"
  bio: "Системный аналитик"
  avatar : "/assets/images/me.jpeg"
  location: Санкт-Петербург
  links:
    - label: "hh.ru"
      icon: "fab fa-fw fa-id-card"
      url: "https://hh.ru/resume/a6fea043ff0c202a370039ed1f52306a444d33"
    - label: "Эта страница на GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/my-awesome-cv/my-awesome-cv.github.io"
    - label: "Учебная страница по Scala"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/scalodrome"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Paris
atom_feed:
  hide: true

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      classes: wide
      header:
        teaser: "/assets/images/Mont-Blanc.webp"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide
      header:
        overlay_image: "/assets/images/Mont-Blanc.webp"
        overlay_filter: 0.3
        #actions:
          #- label: "❤️ Become a Sponsor"
            #url: "https://github.com/sponsors/"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
